#index:
#    path: /
#    controller: App\Controller\DefaultController::index

Create:
    path: /api/v1/user
    controller: App\Controller\RestController::Create

Update:
    path: /api/v1/user/{id}
    controller: App\Controller\RestController::Update
